account/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('register/',views.register,name="register"),
    path('login/',views.login,name="login"),
    path('logout/',views.logout,name="logout"),



]

blog/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('posts/',views.post_list,name="blog_list"),
    path('<int:id>',views.post_detail,name="blog_detail"),
    path('tags/<slug:tags>',views.post_by_tag,name="post_tags"),
    path('category=<slug:category>',views.post_by_category,name="post_categories"),
    path('add_comment',views.add_comment,name="add_comment"),

]

meals/urls.py
from unicodedata import name
from django.urls import path
from . import views



urlpatterns = [
    path('',views.home,name="home"),
    path('meal_list/',views.meal_list,name="meal_list"),
    path('<slug:slug>',views.meal_detail,name="meal_detail"),
    path('search/' , views.meal_search , name='meal_search'),

]

resturant/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('meals.urls' , 'meals') , namespace="meals")),
    path('reservation/', include(('reservation.urls' , 'reservation') , namespace="reservation")),
    path('message/',include(('user.urls' , 'user') , namespace='user')),
    path('blog/',include(('blog.urls' , 'blog') , namespace='blog')),
    path('account/',include(('account.urls' , 'account') , namespace='account')),

]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
{% load static %}

<header>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <div class="full">
                    
                    <a class="logo" href="{% url 'meals:meal_search' %}"><img src="{% static 'site_static/images/logo.png' %}" alt="#" /></a>
                </div>
            </div>
            <div class="col-md-9">
                <div class="full">
                    <div class="right_header_info">
                        <ul>
                            <li class="dinone">Contact Us : <img style="margin-right: 15px;margin-left: 15px;" src="{% static 'site_static/images/phone_icon.png' %}" alt="#"><a href="#">{{site_info.phone}}</a></li>
                            <li class="dinone"><img style="margin-right: 15px;" src="{% static 'site_static/images/mail_icon.png' %}" alt="#"><a href="#">{{site_info.email}}</a></li>
                            <li class="dinone"><img style="margin-right: 15px;height: 21px;position: relative;top: -2px;" src="{% static 'site_static/images/location_icon.png' %}" alt="#"><a href="#">{{site_info.location}}</a></li>
                            <li class="button_user">
                                {% if user.is_authenticated %}
                                <a class="button" href="javascript:{document.getElementById('logout').submit()}">LogOut</a>
                                <form action="{% url 'account:logout' %}" id="logout" method="POST">
                                    {% csrf_token %}
                                    <input type="hidden" name="" id="">
                                 </form>

                                {% else %}
                                <a class="button active" href="{% url 'account:login' %}">Login</a>
                                <a class="button" href="{% url 'account:register' %}">Register</a>
                                {% endif %}
                                
                            </li>
                            <li><img style="margin-right: 15px;" src="{% static 'site_static/images/search_icon.png' %}" alt="#"></li>
                            <li>
                                <button type="button" id="sidebarCollapse">
                                    <img src="{% static 'site_static/images/menu_icon.png'  %}" alt="#">
                                </button>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

templates/includes/message.html
{% if messages %}


{% for message in messages %}

<div id="message" class="container">


    <div class="alert alert-{{message.tags}}" alert-dismissible role="alert">

        <button type="button" class="close" data-dismiss="alert" ><span aria-hidden="true">&times;</span></button>



    <strong>
        {% if message.level == DEFAULT_MESSAGE_LEVEL.ERROR %}
        ERROR : 
        {% else %}
        {{message.tags|title}}
        {% endif %}
    </strong>
    {{message}}

</div>
</div>
{% endfor %}


{% endif %}

templates/includes/poster.html
{% load static %}

<div class="slider_section">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="full">
                    <div id="main_slider" class="carousel vert slide" data-ride="carousel" data-interval="5000">
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <div class="row">
                                    <div class="col-md-5">
                                        <div class="slider_cont">
                                            <h3>Discover Restaurants<br>That deliver near You</h3>
                                            <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
                                            <a class="main_bt_border" href="{% url 'meals:meal_list' %}">Order Now</a>
                                        </div>
                                    </div>
                                    <div class="col-md-7">
                                        <div class="slider_image full text_align_center">
                                            <img class="img-responsive" src="{% static 'site_static/images/burger_slide.png' %}" alt="#" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="carousel-item">
                                <div class="row">
                                    <div class="col-md-5">
                                        <div class="slider_cont">
                                            <h3>Discover Restaurants<br>That deliver near You</h3>
                                            <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
                                            <a class="main_bt_border" href="#">Order Now</a>
                                        </div>
                                    </div>
                                    <div class="col-md-7 full text_align_center">
                                        <div class="slider_image">
                                            <img class="img-responsive" src="{% static 'site_static/images/burger_slide.png' %}" alt="#" />
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a class="carousel-control-prev" href="#main_slider" role="button" data-slide="prev">
                            <i class="fa fa-angle-up"></i>
                        </a>
                        <a class="carousel-control-next" href="#main_slider" role="button" data-slide="next">
                            <i class="fa fa-angle-down"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>