blog/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('posts/',views.post_list,name="blog_list"),
    path('<int:id>',views.post_detail,name="blog_detail"),
    path('tags/<slug:tags>',views.post_by_tag,name="post_tags"),
    path('category=<slug:category>',views.post_by_category,name="post_categories"),
    path('add_comment',views.add_comment,name="add_comment"),

]

resturant/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('meals.urls' , 'meals') , namespace="meals")),
    path('reservation/', include(('reservation.urls' , 'reservation') , namespace="reservation")),
    path('message/',include(('user.urls' , 'user') , namespace='user')),
    path('blog/',include(('blog.urls' , 'blog') , namespace='blog')),
    path('account/',include(('account.urls' , 'account') , namespace='account')),

]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from email.policy import default
from importlib.metadata import requires
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from taggit.managers import TaggableManager
# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    author = models.ForeignKey(User , on_delete=models.CASCADE)
    created = models.DateTimeField(default=timezone.now)
    category = models.ForeignKey('Category' , on_delete=models.SET_NULL , null=True , blank=True)
    image = models.ImageField(upload_to='blog/' , default='blog/163529.jpg')
    tags = TaggableManager()

    def __str__(self) :
        return self.title

    class Meta:
        verbose_name = "Post"
        verbose_name_plural = "Posts"   



class Category(models.Model):
    name = models.CharField(max_length=225)   

    def __str__(self) :
        return self.name

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"    


class Comments(models.Model):
    user_id = models.IntegerField(default=1)
    post_id = models.IntegerField(default=1)
    email = models.EmailField()
    phone = models.IntegerField()
    text = models.TextField()
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.text)

    class Meta:
        verbose_name = "Comment"
        verbose_name_plural = "Comments"     

blog/forms.py
from django import forms
from .models import Comments



class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = '__all__'

blog/views.py
from multiprocessing import context
from django.shortcuts import redirect, render
from requests import request
from . import models
from .forms import CommentsForm
from django.core.paginator import Paginator
from sitedetails.models import SiteDetails
from django.contrib.auth.models import User
# Create your views here.


def post_list(request):
    site_info = SiteDetails.objects.last() 
    post_list = models.Post.objects.all()
    paginator = Paginator(post_list , 2)
    page = request.GET.get('page')
    post_list = paginator.get_page(page)

    context = {
         "site_info" : site_info,     
        "post_list" : post_list}   

    return render(request , 'blog/list.html' , context)



def post_detail(request , id):
    site_info = SiteDetails.objects.last() 
    post = models.Post.objects.get(id=id)
    comments = models.Comments.objects.filter(post_id=id)
    categories = models.Category.objects.all()


    context = {"post" : post , "categories" : categories , "comments" : comments  ,    "site_info" : site_info, }
    return render(request , "blog/detail.html" , context)
        

def add_comment(request):
    if request.method == "POST":
        user_id = request.POST['user_id']
        post_id = request.POST['post_id']
        email = request.POST['email']
        phone = request.POST['phone']
        text = request.POST['text']
        created = request.POST['created']
        commnet = models.Comments(user_id = user_id , post_id = post_id , email = email , phone = phone , text = text , created = created)
        commnet.save()

        return redirect("blog:blog_list")


         

def post_by_tag(request , tags):
    site_info = SiteDetails.objects.last()
    post_by_tags = models.Post.objects.filter(tags__name__in = {tags})
    context = {"post_list" : post_by_tags ,    "site_info" : site_info, }
    return render(request , 'blog/list.html' , context)



def post_by_category(request , category):
    site_info = SiteDetails.objects.last()
    post_by_category = models.Post.objects.filter(category__name =category)
    context = {"post_list" : post_by_category ,    "site_info" : site_info, }
    return render(request , 'blog/list.html' , context)

blog/templates/blog/detail.html
{% extends 'base.html' %}


{% block title %}
{{post.title}}
{% endblock title %}

{% block body %}


{% load static %}



    <!-- end header -->
<div class="yellow_bg">
   <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <div class="title">
                     <h2>{{post.title}}</h2>
                    
                  </div>
               </div>
            </div>
          </div>
</div>

<!-- blog -->
<div class="blog">
  
  <div class="container">

    <div class="row">
      <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 mar_bottom">
<div class="col-xs-12">
        <div class="blog_box blog_box_inline col-xl-12 col-lg-6 col-md-6 col-sm-12">
          <div class="blog_img_box">
            <figure><img src='../../media/{{post.image}}' alt="#"/>
         
            </figure>
          </div>
          <h3>{{post.title}}</h3>
        </div>
        <div class="blog_box blog_box_inline col-xl-12 col-lg-6 col-md-6 col-sm-12">
           <div class="textboxfordetailmeal">
               <div>     <h4>Created At </h4>
                <span>{{post.created}}</span> <strong></strong></div>



                    <div>     <h4>Text : </h4>
                        <span class="content-blog">{{post.content}} </span><strong></strong></div>


                        <div>     <h4>Category</h4>
                          <span>{{post.category}} </span><strong></strong></div>


   
        </div>
          </div>
        </div>
       
      </div> 


      <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 mar_bottom">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 mar_bottom">
          <div class="post_category">

            <h3>Categories</h3>
  
            <ul>
              {% for category in categories %}
              <a href="{% url 'blog:post_categories' category %}">
              <li>
                {{category.name}}
              </li>
            </a>
              {% endfor %}
            </ul>
          </div>
      </div>
      <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 mar_bottom">
        <div class="post_category">

          <h3>Tags</h3>

          <ul>
        {% for tag in post.tags.all %}
        <a href="{% url 'blog:post_tags' tag%}">
            <li>
              {{tag}}
            </li>
        </a>    
            {% endfor %}
          </ul>
        </div>
    </div>
    </div>


  </div>



</div>

<div class="footer commentSection">
  <div class="container-fluid">
      <div class="row">
        <div class=" col-md-12">
          <h2>Leave Your<strong class="black">Comment</strong></h2>
        </div>
          <div class="col-xl-12 col-lg-12 col-md-6 col-sm-12">
        

               <form action="{%url 'blog:add_comment' %}" class="main_form" method="post">
                  <div class="row">

                    {% csrf_token %}
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
<span class="select_comment">

  <input type="text"id="" name="user_id"  value="{{user.id}}" placeholder="Leave your name"

  
  >

</span>
               </div>

               <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                <span class="select_comment">
              Post 
            <input type="text" name="post_id" id="" value="{{post.id}}" placeholder="">
                </span>
                               </div>               
                      <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                          <input class="form-control" placeholder="Email" type="email" name="email">
                      </div>
                      <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                          <input class="form-control" placeholder="Phone" type="number" name="phone">
                      </div>
                      <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                        <input class="form-control" placeholder="Date and time" type="date" name="created">
                    </div>
                      <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                          <textarea class="textarea" placeholder="Message" type="text" name="text"></textarea>
                      </div>
                      <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
                          <button type="submit" class="send">Send</button>
                      </div>
                 
               
                </div>
              </form> 

              <!-- <form action="" method="POST" enctype="multipart/form-data" class="CommentForm">

                {% csrf_token %}
                {{comment_form}}

                <button type="submit">Leave It</button>
              </form> -->

          

          </div>

          <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 mar_bottom">
            <div class="post_category post_comments">
    
              <h1>Comments</h1>
    
              <ul>
            {% for comment in comments %}
            <a href="#">
                <li>
                  <h3>{{comment.email}}</h3>
                  <section>{{comment.text}}</section>
             
                </li>
            </a>    
                {% endfor %}
              </ul>
            </div>
        </div>
<!-- end blog -->

{% endblock %}

blog/templates/blog/list.html
{% extends 'base.html' %}


{% block title %}

Blog List

{% endblock title %}

{% block body %}


{% load static %}
<!-- blog -->
<div class="blog">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="title">
          <i><img src="{% static 'site_static/images/title.png' %}" alt="#"/></i>
          
          <span>when looking at its layout. The point of using Lorem</span>
        </div>
      </div>
    </div>
    <div class="row">

        {%for post in post_list%}
      
     
            <div class="col-xl-6 col-lg-6 col-md-4 col-sm-12 mar_bottom blog_posts">
                <a href="{% url 'blog:blog_detail' post.id%}">
        <div class="blog_box">
          <div class="blog_img_box">
            <figure><img src='../../media/{{post.image}}' alt="#"/>
             <span>{{post.created}}</span>
            </figure>
          </div>
          <h3>{{post.title}}</h3>
          <p>Author : <strong>{{post.author}}</strong></p>
          <a class="button" href="{% url 'blog:blog_detail' post.id %}">See More</a>
        </div>
    </a>
      </div>

      {% endfor %}
<div class="col-xs-12 col-xl-12 col-sm-12 col-lg-12">

  {% if post_list.has_other_pages %}
  <div class="col-xs-12 col-xl-12 col-sm-12 col-lg-12">

    <div class="pagination">
      {% if post_list.has_previous %}
      <a href="?page={{post_list.previous_page_number}}">&laquo;</a>
      {% endif %}
      {% for pages in post_list.paginator.page_range %}
      {% if post_list.number == pages %}
      <a href="#">{{pages}}</a>
      {% else %}
      <a href="?page={{pages}}">{{pages}}</a>
{% endif %}      
{% endfor %}
      {% if post_list.has_next %}
      <a href="?page={{post_list.next_page_number}}">&raquo;</a>
      {% endif %}
    </div>
        
    
  </div>   
  {% endif %}
</div>
    </div>
  </div>
</div>
<!-- end blog -->


{% endblock %}


  