blog/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('posts/',views.post_list,name="blog_list"),
    path('<int:id>',views.post_detail,name="blog_detail"),
    path('tags/<slug:tags>',views.post_by_tag,name="post_tags"),
    path('category=<slug:category>',views.post_by_category,name="post_categories"),
    path('add_comment',views.add_comment,name="add_comment"),

]

meals/urls.py
from unicodedata import name
from django.urls import path
from . import views



urlpatterns = [
    path('',views.home,name="home"),
    path('meal_list/',views.meal_list,name="meal_list"),
    path('<slug:slug>',views.meal_detail,name="meal_detail"),
    path('search/' , views.meal_search , name='meal_search'),

]

resturant/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('meals.urls' , 'meals') , namespace="meals")),
    path('reservation/', include(('reservation.urls' , 'reservation') , namespace="reservation")),
    path('message/',include(('user.urls' , 'user') , namespace='user')),
    path('blog/',include(('blog.urls' , 'blog') , namespace='blog')),
    path('account/',include(('account.urls' , 'account') , namespace='account')),

]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meals/models.py
from pyexpat import model
from django.db import models
from django.utils.text import slugify

# Create your models here.


class Meals(models.Model):
    name = models.CharField(max_length=225)
    description = models.TextField()
    price = models.DecimalField(max_digits=6,decimal_places=2)
    prepration_time = models.IntegerField()
    image = models.ImageField(upload_to='meals/')
    slug = models.SlugField(blank=True,null=True)
    category = models.ForeignKey("Category" , on_delete=models.SET_NULL , null=True , blank=True)
    
    class Meta:
        verbose_name = "Meal"
        verbose_name_plural = "Meals"


    def save(self , *args , **kwargs):
        if not self.slug and self.name:
            self.slug = slugify(self.name)
        super(Meals , self).save(*args , **kwargs)    

    def __str__(self) -> str:
        return self.name


class Category(models.Model):   
    name = models.CharField(max_length=225)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self) :
        return self.name    

meals/views.py
from urllib import response
from django.http import HttpResponse
from django.shortcuts import render
from .models import Meals , Category
from blog.models import Post
from sitedetails.models import SiteDetails

# Create your views here.


def home(request):

    meal_list = Meals.objects.all()
    category_list = Category.objects.all()
    blog_list = Post.objects.all()
    site_info = SiteDetails.objects.last()
    context = {
        "meal_list" : meal_list,
        "category_list" : category_list,
        "blog_list" : blog_list,
        "site_info" : site_info
        
        }

    return render(request , 'meals/home.html' , context)    



def meal_list(request):
    meals = Meals.objects.all()
    categories = Category.objects.all()
    site_info = SiteDetails.objects.last()
    context = {
        "site_info" : site_info,
        "meals" : meals,
        "categories" : categories
        }
    return render(request , 'meals/list.html' , context)



def meal_detail(request , slug):
    
    try:
        meal_detail = Meals.objects.get(slug = slug)
    except meal_detail.DoesNotExist:
        meal_detail = None

    site_info = SiteDetails.objects.last() 
    context = {
        "site_info" : site_info,
        "meal_detail" : meal_detail}
    return render(request , 'meals/detail.html' , context)


def meal_search(request):

    meals = Meals.objects.all()
    allCategories = Category.objects.all()
    site_info = SiteDetails.objects.last() 
    if 'name' in request.GET:
        name = request.GET['name']
        if name:
            meals = Meals.objects.filter(name__icontains = name)
    if 'categories' in request.GET:
        categories = request.GET['categories']
        if categories:
            meals = Meals.objects.filter(category__name__icontains=categories)

    if 'price-min' in request.GET:
        minPrice = request.GET['price-min']
        maxPrice = request.GET['price-max']
        if minPrice and maxPrice:
            cars = Meals.objects.filter(price__gte = minPrice , price__lte = maxPrice) 
    context = {
        "site_info" : site_info,
        "categories" : allCategories,
        "meals" : meals}

    return render(request , 'meals/search.html' , context)               

            

meals/templates/meals/detail.html
{% extends 'base.html' %}

{% block title %}
{{meal_detail.name}}
{% endblock title %}
{% block body %}


{% load static %}



    <!-- end header -->
<div class="yellow_bg">
   <div class="container">
            <div class="row">
               <div class="col-md-12">
                  <div class="title">
                     <h2>{{meal_detail.name}}</h2>
                    
                  </div>
               </div>
            </div>
          </div>
</div>

<!-- blog -->
<div class="blog">
  <div class="container">

    <div class="row">
      <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 mar_bottom">

        <div class="blog_box blog_box_inline col-xl-6 col-lg-6 col-md-6 col-sm-12">
          <div class="blog_img_box">
            <figure><img src='../media/{{meal_detail.image}}' alt="#"/>
             <span>{{meal_detail.price}}$</span>
            </figure>
          </div>
          <h3>{{meal_detail.name}}</h3>
        </div>
        <div class="blog_box blog_box_inline col-xl-6 col-lg-6 col-md-6 col-sm-12">
           <div class="textboxfordetailmeal">
               <div>     <h4>Prepration Time : </h4>
                <span>{{meal_detail.prepration_time}}</span> <strong>Minutes</strong></div>



                    <div>     <h4>Only</h4>
                        <span>{{meal_detail.price}} </span><strong>$</strong></div>


                        <div>     <h4>Category</h4>
                          <span>{{meal_detail.category}} </span><strong></strong></div>


   
        </div>
          </div>
      </div>

    </div>
  </div>
</div>


<!-- end blog -->




{% endblock %}

meals/templates/meals/home.html
{% extends 'base.html' %}


{% block title %}
Home
{% endblock title %}

{% block body %}


{% load static %}
    <!-- section -->
    <section class="resip_section">
<div class="container">
<div class="row">
         <div class="col-md-12">
       <div class="ourheading">
    <h2>Our Foods</h2>
  </div>
</div>    
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="owl-carousel owl-theme">

                {% for meal in meal_list %}


<a href="{%url 'meals:meal_detail' meal.slug%}">
                <div class="item">
                    <div class="product_blog_img">
                        <img src='../media/{{meal.image}}' alt="#" />
                    </div>
                    <div class="product_blog_cont">
                        <h3>{{meal.name}}</h3>
                        <h4><span class="theme_color">$</span>{{meal.price}}</h4>
                    </div>
                </div>
</a>
              {% endfor %}

            </div>
        </div>
    </div>
</div>
</div>

<div class="row CategoryList">
    <div class="col-md-12">

        <div class="col-xs-12">
            <div class="tabs">

            {%for category in category_list %}
       
              <div class="tab">
                <input type="radio" name="css-tabs" id="{{category.name}}" checked class="tab-switch">
                <label for="{{category.name}}" class="tab-label">{{category.name}}</label>
          
                 
                <div class="tab-content">

           {% for meal in meal_list %}

            {% if meal.category == category %}
<li>    {{meal.name}}</li>
        
            {% endif %}
            {% endfor %}

         
                <img src="{% static 'site_static/images/burger_slide.png' %}" alt="">
        
        </div>
              </div>

              {% endfor %}
            </div>
          </div>
    
    
    </div>

</div>



</div>


<section class="vh-100" style="background-color: #eee;">
    <div class="container h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-lg-12 col-xl-11">
          <div class="card text-black" style="border-radius: 25px;">
            <div class="card-body p-md-5">
              <div class="row justify-content-center">
                <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1 blogHeader">
  
<h2>CHECK OUR BLOG!</h2>
<p>Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.</p>  
<a href="{% url 'blog:blog_list' %}">            
  <button>Observe!</button>
</a>
                </div>
                <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-right order-1 order-lg-2 blogImage pull-right right">
                 
                  <img src="{% static 'site_static/images/2-20093_transparent-background-chef-images-png-png-download-removebg-preview.png' %}"
                    class="img-fluid" alt="Sample image">
               
          
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

</section>


{% endblock %}

meals/templates/meals/list.html
{% extends 'base.html' %}

{% block title %}
Meals List
{% endblock title %}


{% block body %}

{% load static %}


<div class="container mt-100">
<div class="row">

    <form action="{% url 'meals:meal_search' %}" class="search-home">
        {% csrf_token %}
     <div>
     <input type="search" class="form-control rounded" placeholder="Search" name="name" />
     <select name="categories" id="">
        <option value="State" disabled>Categories</option>
        {% for category in categories %}
        <option value="{{category.name}}">{{category.name}}</option>
        {% endfor %}

 

     </select>




     <div data-role="rangeslider" class="rangeslider">
        <label for="price-min">Min Price:</label>
        <input type="range" name="price-min" id="price-min" value="200" min="0" max="1000">
        <label for="price-max">Max Price:</label>
        <input type="range" name="price-max" id="price-max" value="800" min="0" max="1000">
      </div>

     </div>
     <div>
     <button type="submit" class="btn btn-outline-primary">search</button>
     </div>
     </form>

</div>                   		                                                   
<div class="row">
    {% for meal in meals %}
<div class="col-md-4 col-sm-6 mealList">
<div class="card mb-30"><a class="card-img-tiles" href="#" data-abc="true">
<div class="inner">
<div class="main-img"><img src="{{ meal.image.url }}" alt="Category"></div>
</div></a>
<div class="card-body text-center">
<h4 class="card-title">{{meal.name}}</h4>
<p class="text-muted">Starting from ${{meal.price}}</p><a class="btn btn-outline-primary btn-sm" href="{% url 'meals:meal_detail' meal.slug %}" data-abc="true">View Products</a>
</div>
</div>
</div>
{% endfor %}
</div>
</div>


{% endblock %}

meals/templates/meals/search.html
{% extends 'base.html' %}



{% block title %}
Search Resault
{% endblock title %}

{% block body %}

{% load static %}


<div class="container mt-100">
<div class="row">


   <form action="{% url 'meals:meal_search' %}" class="search-home">
      {% csrf_token %}
   <div>
   <input type="search" class="form-control rounded" placeholder="Search" name="name" />
   <select name="categories" id="">
      <option value="State" disabled>Categories</option>
      {% for category in categories %}
      <option value="{{category.name}}">{{category.name}}</option>
      {% endfor %}



   </select>




   <div data-role="rangeslider" class="rangeslider">
      <label for="price-min">Min Price:</label>
      <input type="range" name="price-min" id="price-min" value="200" min="0" max="1000">
      <label for="price-max">Max Price:</label>
      <input type="range" name="price-max" id="price-max" value="800" min="0" max="1000">
    </div>

   </div>
   <div>
   <button type="submit" class="btn btn-outline-primary">search</button>
   </div>
   </form>

</div>                   		                                                   
<div class="row">
    {% for meal in meals %}
<div class="col-md-4 col-sm-6 mealList">
<div class="card mb-30"><a class="card-img-tiles" href="#" data-abc="true">
<div class="inner">
<div class="main-img"><img src="{{ meal.image.url }}" alt="Category"></div>
</div></a>
<div class="card-body text-center">
<h4 class="card-title">{{meal.name}}</h4>
<p class="text-muted">Starting from ${{meal.price}}</p><a class="btn btn-outline-primary btn-sm" href="{% url 'meals:meal_detail' meal.slug %}" data-abc="true">View Products</a>
</div>
</div>
</div>
{% endfor %}
</div>
</div>


{% endblock %}