blog/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('posts/',views.post_list,name="blog_list"),
    path('<int:id>',views.post_detail,name="blog_detail"),
    path('tags/<slug:tags>',views.post_by_tag,name="post_tags"),
    path('category=<slug:category>',views.post_by_category,name="post_categories"),
    path('add_comment',views.add_comment,name="add_comment"),

]

meals/urls.py
from unicodedata import name
from django.urls import path
from . import views



urlpatterns = [
    path('',views.home,name="home"),
    path('meal_list/',views.meal_list,name="meal_list"),
    path('<slug:slug>',views.meal_detail,name="meal_detail"),
    path('search/' , views.meal_search , name='meal_search'),

]

reservation/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.reserve_table,name="add_reserve"),

]

resturant/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('meals.urls' , 'meals') , namespace="meals")),
    path('reservation/', include(('reservation.urls' , 'reservation') , namespace="reservation")),
    path('message/',include(('user.urls' , 'user') , namespace='user')),
    path('blog/',include(('blog.urls' , 'blog') , namespace='blog')),
    path('account/',include(('account.urls' , 'account') , namespace='account')),

]

urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path 
from . import views



urlpatterns = [
    path('about/',views.about,name='about'),
    path("send_email/",views.send_email,name='send_email'),
    path("email_success/",views.email_success_sent,name='email_success')

]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>{% block title %} {% endblock title %}</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- bootstrap css -->
    <link rel="stylesheet" href="{% static 'site_static/css/bootstrap.min.css' %}">
    <!-- owl css -->
    <link rel="stylesheet" href="{% static 'site_static/css/owl.carousel.min.css' %}">
    <!-- style css -->
    <link rel="stylesheet" href="{% static 'site_static/css/style.css' %}">
    <!-- responsive-->
    <link rel="stylesheet" href="{% static 'site_static/css/responsive.css' %}">
    <!-- awesome fontfamily -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->

<body class="main-layout">
    <!-- loader  -->
    <div class="loader_bg">
        <div class="loader"><img src="{% static 'site_static/images/loading.gif' %}" alt="" /></div>
    </div>

    <div class="wrapper">
    <!-- end loader -->

     <div class="sidebar">
            <!-- Sidebar  -->
            <nav id="sidebar">

                <div id="dismiss">
                    <i class="fa fa-arrow-left"></i>
                </div>

                <ul class="list-unstyled components">

                    <li class="active">
                        <a href="/meals">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'user:about' %}">About</a>
                    </li>

                    <li>
                        <a href="{% url 'meals:meal_list' %}">Meals</a>
                    </li>
                    <li>
                        <a href="{% url 'reservation:add_reserve' %}">Recipe</a>
                    </li>
                    <li>
                        <a href="{% url 'blog:blog_list' %}">Blog</a>
                    </li>
                    <li>
                        <a href="{% url 'user:send_email' %}">Contact Us</a>
                    </li>
                </ul>

            </nav>
        </div>

    <div id="content">
    <!-- header -->
 {% include 'includes/header.html' %}
    <!-- end header -->
    <!-- start slider section -->
    {% include 'includes/poster.html' %}
 
    <!-- end slider section -->




{% block body %}

 

{% endblock body %}



<!-- Deleted Section -->






    <!-- footer -->
    <fooetr>
        <div class="footer">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-12">
                        <div class="footer_logo">
                          <a href="index.html"><img src="{% static 'site_static/images/logo1.jpg' %}" alt="logo" /></a>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <ul class="lik">
                            <li class="active"> <a href="index.html">Home</a></li>
                            <li> <a href="about.html">About</a></li>
                            <li> <a href="recipe.html">Recipe</a></li>
                            <li> <a href="blog.html">Blog</a></li>
                            <li> <a href="contact.html">Contact us</a></li>
                        </ul>
                    </div>
                    <div class="col-md-12">
                        <div class="new">
                            <h3>Newsletter</h3>
                            <form class="newtetter">
                                <input class="tetter" placeholder="Your email" type="text" name="Your email">
                                <button class="submit">Subscribe</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="copyright">
                <div class="container">
                    <p>© 2019 All Rights Reserved. Back-End by<a href="instagram.com/im_sina"> Sina Heydari Nezhad</a></p>
                </div>
            </div>
        </div>
    </fooetr>
    <!-- end footer -->

    </div>
    </div>
    <div class="overlay"></div>
    <!-- Javascript files-->
    <script src="{% static 'site_static/js/jquery.min.js' %}"></script>
    <script src="{% static 'site_static/js/popper.min.js' %}"></script>
    <script src="{% static 'site_static/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'site_static/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'site_static/js/custom.js' %}"></script>
     <script src="{% static 'site_static/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
    
     <script src="{% static 'site_static/js/jquery-3.0.0.min.js' %}"></script>
     <script defer src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" integrity="sha384-rOA1PnstxnOBLzCLMcre8ybwbTmemjzdNlILg8O7z1lUkLXozs4DHonlDtnE7fpc" crossorigin="anonymous"></script>
   <script type="text/javascript">
        $(document).ready(function() {
            $("#sidebar").mCustomScrollbar({
                theme: "minimal"
            });

            $('#dismiss, .overlay').on('click', function() {
                $('#sidebar').removeClass('active');
                $('.overlay').removeClass('active');
            });

            $('#sidebarCollapse').on('click', function() {
                $('#sidebar').addClass('active');
                $('.overlay').addClass('active');
                $('.collapse.in').toggleClass('in');
                $('a[aria-expanded=true]').attr('aria-expanded', 'false');
            });
        });
    </script>

    <style>
    #owl-demo .item{
        margin: 3px;
    }
    #owl-demo .item img{
        display: block;
        width: 100%;
        height: auto;
    }
    </style>

     
      <script>
         $(document).ready(function() {
           var owl = $('.owl-carousel');
           owl.owlCarousel({
             margin: 10,
             nav: true,
             loop: true,
             responsive: {
               0: {
                 items: 1
               },
               600: {
                 items: 2
               },
               1000: {
                 items: 5
               }
             }
           })
         })
      </script>

</body>

</html>